BEGIN;

-- -----------------------------------------------------------------------------
-- Festo CP Lab process-state catalog
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS festo_state_codes (
    state_code INTEGER PRIMARY KEY,
    process_state VARCHAR(64) NOT NULL UNIQUE,
    top_cover VARCHAR(8),
    description TEXT NOT NULL,
    CHECK (top_cover IS NULL OR top_cover IN ('blue', 'red'))
);

INSERT INTO festo_state_codes (state_code, process_state, top_cover, description)
VALUES
    (0,   'INITIAL',                         NULL,   'Initial or undefined process state'),
    (100, 'CAMERA_COMPLETED',                NULL,   'Camera station completed successfully'),
    (200, 'DRILLING_COMPLETED',              NULL,   'Drilling station completed successfully'),
    (300, 'BLUE_STAGE_COMPLETED_RED_REQUIRED','red', 'Blue station completed by intentionally skipping blue cover; red cover required'),
    (301, 'BLUE_COVER_INSTALLED',            'blue', 'Blue top cover installed successfully'),
    (401, 'TOP_COVER_COMPLETED_BLUE',        'blue', 'Top-cover stage completed with blue top cover'),
    (402, 'TOP_COVER_COMPLETED_RED',         'red',  'Top-cover stage completed with red top cover'),
    (501, 'PRESS_COMPLETED_BLUE',            'blue', 'Press completed successfully with blue top cover'),
    (502, 'PRESS_COMPLETED_RED',             'red',  'Press completed successfully with red top cover'),
    (601, 'LABELING_COMPLETED_BLUE',         'blue', 'Labeling stage completed with blue top cover'),
    (602, 'LABELING_COMPLETED_RED',          'red',  'Labeling stage completed with red top cover'),
    (701, 'DISPATCH_COMPLETED_BLUE',         'blue', 'Dispatch completed successfully with blue top cover'),
    (702, 'DISPATCH_COMPLETED_RED',          'red',  'Dispatch completed successfully with red top cover')
ON CONFLICT (state_code) DO UPDATE SET
    process_state = EXCLUDED.process_state,
    top_cover = EXCLUDED.top_cover,
    description = EXCLUDED.description;

-- Allowed product-state transitions. Carrier reset/reuse is handled separately
-- from product-state progression and therefore is intentionally not listed here.
CREATE TABLE IF NOT EXISTS festo_state_transitions (
    from_state INTEGER NOT NULL REFERENCES festo_state_codes(state_code),
    to_state INTEGER NOT NULL REFERENCES festo_state_codes(state_code),
    PRIMARY KEY (from_state, to_state)
);

INSERT INTO festo_state_transitions (from_state, to_state)
VALUES
    (0, 100),
    (100, 200),
    (200, 300),
    (200, 301),
    (300, 402),
    (301, 401),
    (401, 501),
    (402, 502),
    (501, 601),
    (502, 602),
    (601, 701),
    (602, 702)
ON CONFLICT DO NOTHING;

-- -----------------------------------------------------------------------------
-- Physical carriers
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS carriers (
    carrier_id INTEGER PRIMARY KEY,
    current_state_code INTEGER NOT NULL DEFAULT 0
        REFERENCES festo_state_codes(state_code),
    status VARCHAR(16) NOT NULL DEFAULT 'AVAILABLE',
    last_seen_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (status IN ('AVAILABLE', 'IN_USE', 'UNKNOWN'))
);

-- -----------------------------------------------------------------------------
-- Physical fuse-box products / digital twins
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS parts (
    part_number BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_carrier_id INTEGER REFERENCES carriers(carrier_id),
    carrier_link_active BOOLEAN NOT NULL DEFAULT FALSE,

    inspection_result BOOLEAN,
    bottom_cover VARCHAR(8),
    fuse_configuration VARCHAR(8),
    top_cover VARCHAR(8),

    state_code INTEGER NOT NULL DEFAULT 0
        REFERENCES festo_state_codes(state_code),
    status VARCHAR(24) NOT NULL DEFAULT 'IN_PRODUCTION',
    dispatch_position SMALLINT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    dispatched_at TIMESTAMPTZ,
    stored_at TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ,

    CHECK (bottom_cover IS NULL OR bottom_cover IN ('blue', 'red', 'black')),
    CHECK (fuse_configuration IS NULL OR fuse_configuration IN ('none', 'upper', 'lower', 'both')),
    CHECK (top_cover IS NULL OR top_cover IN ('blue', 'red')),
    CHECK (dispatch_position IS NULL OR dispatch_position IN (1, 2)),
    CHECK (status IN (
        'IN_PRODUCTION',
        'WAITING_PICKUP',
        'STORAGE_RESERVED',
        'STORED',
        'DELIVERY_RESERVED',
        'DELIVERED',
        'SCRAPPED'
    )),
    CHECK (carrier_link_active = FALSE OR source_carrier_id IS NOT NULL)
);

-- A physical carrier can be actively linked to only one product at a time.
CREATE UNIQUE INDEX IF NOT EXISTS ux_parts_active_carrier
    ON parts(source_carrier_id)
    WHERE carrier_link_active = TRUE;

CREATE INDEX IF NOT EXISTS ix_parts_status
    ON parts(status);

CREATE INDEX IF NOT EXISTS ix_parts_configuration
    ON parts(bottom_cover, top_cover, fuse_configuration);

CREATE INDEX IF NOT EXISTS ix_parts_state_code
    ON parts(state_code);

-- -----------------------------------------------------------------------------
-- Process history
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS part_process_events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_number BIGINT NOT NULL REFERENCES parts(part_number) ON DELETE CASCADE,
    carrier_id INTEGER REFERENCES carriers(carrier_id),
    station VARCHAR(32),
    event_type VARCHAR(32) NOT NULL,
    old_state_code INTEGER REFERENCES festo_state_codes(state_code),
    new_state_code INTEGER REFERENCES festo_state_codes(state_code),
    success BOOLEAN NOT NULL DEFAULT TRUE,
    details JSONB NOT NULL DEFAULT '{}'::JSONB,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_part_process_events_part_time
    ON part_process_events(part_number, occurred_at DESC);

CREATE INDEX IF NOT EXISTS ix_part_process_events_carrier_time
    ON part_process_events(carrier_id, occurred_at DESC);

-- Camera inspection attempts are tracked separately because a failed attempt
-- may occur before a permanent part number is allocated.
CREATE TABLE IF NOT EXISTS inspection_events (
    inspection_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrier_id INTEGER NOT NULL REFERENCES carriers(carrier_id),
    part_number BIGINT REFERENCES parts(part_number) ON DELETE SET NULL,
    result BOOLEAN NOT NULL,
    bottom_cover VARCHAR(8),
    fuse_configuration VARCHAR(8),
    details JSONB NOT NULL DEFAULT '{}'::JSONB,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (bottom_cover IS NULL OR bottom_cover IN ('blue', 'red', 'black')),
    CHECK (fuse_configuration IS NULL OR fuse_configuration IN ('none', 'upper', 'lower', 'both'))
);

CREATE INDEX IF NOT EXISTS ix_inspection_events_carrier_time
    ON inspection_events(carrier_id, occurred_at DESC);

-- -----------------------------------------------------------------------------
-- ROS2-managed 3 x 10 storage grid
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS storage_slots (
    slot_id VARCHAR(3) PRIMARY KEY,
    row_index SMALLINT NOT NULL,
    column_index SMALLINT NOT NULL,
    status VARCHAR(12) NOT NULL DEFAULT 'EMPTY',
    part_number BIGINT UNIQUE REFERENCES parts(part_number),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (row_index BETWEEN 1 AND 3),
    CHECK (column_index BETWEEN 1 AND 10),
    CHECK (status IN ('EMPTY', 'RESERVED', 'OCCUPIED')),
    CHECK (
        (status = 'EMPTY' AND part_number IS NULL)
        OR
        (status IN ('RESERVED', 'OCCUPIED') AND part_number IS NOT NULL)
    ),
    UNIQUE (row_index, column_index)
);

INSERT INTO storage_slots (slot_id, row_index, column_index, status, part_number)
SELECT
    'S' || LPAD(slot_number::TEXT, 2, '0'),
    ((slot_number - 1) / 10) + 1,
    ((slot_number - 1) % 10) + 1,
    'EMPTY',
    NULL
FROM generate_series(1, 30) AS slot_number
ON CONFLICT (slot_id) DO NOTHING;

-- -----------------------------------------------------------------------------
-- Read model for the complete ROS2 product digital twin
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW part_digital_twins AS
SELECT
    p.part_number,
    p.source_carrier_id AS carrier_id,
    p.carrier_link_active,
    p.inspection_result,
    p.bottom_cover,
    p.fuse_configuration,
    p.top_cover,
    p.state_code,
    fsc.process_state,
    p.status,
    p.dispatch_position,
    ss.slot_id AS storage_position,
    p.created_at,
    p.updated_at,
    p.dispatched_at,
    p.stored_at,
    p.delivered_at
FROM parts p
JOIN festo_state_codes fsc
    ON fsc.state_code = p.state_code
LEFT JOIN storage_slots ss
    ON ss.part_number = p.part_number;

-- Read model used by future deterministic inventory skills.
CREATE OR REPLACE VIEW available_stored_parts AS
SELECT
    p.part_number,
    p.bottom_cover,
    p.top_cover,
    p.fuse_configuration,
    ss.slot_id AS storage_position
FROM parts p
JOIN storage_slots ss
    ON ss.part_number = p.part_number
WHERE p.status = 'STORED'
  AND ss.status = 'OCCUPIED';

COMMIT;
