BEGIN;

CREATE TABLE IF NOT EXISTS delivery_requests (
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bottom_cover VARCHAR(8) NOT NULL,
    top_cover VARCHAR(8) NOT NULL,
    fuse_configuration VARCHAR(8) NOT NULL,
    quantity INTEGER NOT NULL,
    destination VARCHAR(64) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'RESERVING',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    CHECK (bottom_cover IN ('blue', 'red', 'black')),
    CHECK (top_cover IN ('blue', 'red')),
    CHECK (fuse_configuration IN ('none', 'upper', 'lower', 'both')),
    CHECK (quantity > 0),
    CHECK (status IN (
        'RESERVING',
        'QUEUED',
        'IN_PROGRESS',
        'COMPLETED',
        'FAILED',
        'POSITION_UNKNOWN',
        'CANCELLED'
    ))
);

CREATE TABLE IF NOT EXISTS delivery_request_items (
    request_id BIGINT NOT NULL
        REFERENCES delivery_requests(request_id) ON DELETE CASCADE,
    part_number BIGINT NOT NULL
        REFERENCES parts(part_number),
    slot_id VARCHAR(3) NOT NULL
        REFERENCES storage_slots(slot_id),
    status VARCHAR(24) NOT NULL DEFAULT 'RESERVED',
    robot_job_id UUID,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (request_id, part_number),
    UNIQUE (part_number),
    CHECK (status IN (
        'RESERVED',
        'QUEUED',
        'RUNNING',
        'DELIVERED',
        'RELEASED',
        'POSITION_UNKNOWN',
        'CANCELLED'
    ))
);

CREATE INDEX IF NOT EXISTS ix_delivery_requests_status
    ON delivery_requests(status, created_at);

CREATE INDEX IF NOT EXISTS ix_delivery_request_items_request_status
    ON delivery_request_items(request_id, status);

COMMIT;
